### ISSUE TITLE
The Name Full Stack Web Developer breaks into a another line.

### ISSUE THREAD

**Issue by BulletStormXT** [BulletStormXT/portfolio#15]
Helpful is `&nbsp;` between the words. This means **N**o **B**reaking **S**Pace

**Comment by BulletStormXT** [comment]
Thanks.
`Full&nbsp;Stack&nbsp;Web&nbsp;Developer`

**Comment by BulletStormXT** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Portfolio bearbeiten](https://trello.com/c/5KFxCS6H/40-portfolio-bearbeiten)

**Comment by arjun-gr** [comment]
I see what you mean, in responsive mobile screens the full stack web developer breaks into new line, an easier approach would be just changing the span from inline to display block. I think, what do you think?

**Comment by BulletStormXT** [comment]
thanks guy. i did not need help at the time. i did not know that good first issue is public :D

**Comment by BulletStormXT** [comment]
Done with merge #37 #
